#!/usr/bin/env python3
# /// script
# requires-python = ">=3.10"
# dependencies = ["pytest>=7.0"]
# ///
"""Tests for pipeline-guard.py"""

import sys
from pathlib import Path
from importlib.util import spec_from_file_location, module_from_spec

import pytest

sys.path.insert(0, str(Path(__file__).parent.parent))

spec = spec_from_file_location(
    "pipeline_guard",
    Path(__file__).parent.parent / "pipeline-guard.py",
)
mod = module_from_spec(spec)
spec.loader.exec_module(mod)


def test_detect_suno_package_positive():
    assert mod.detect_suno_package("## Your Suno Package\n...")
    assert mod.detect_suno_package("### Copy-Ready: Style Prompt v5")
    assert mod.detect_suno_package("## Copy-Ready Lyrics\n[Verse]")


def test_detect_suno_package_negative():
    assert not mod.detect_suno_package("Just a normal chat about music.")
    assert not mod.detect_suno_package("Let's talk about the band direction.")


def test_extract_tool_uses_nested_message_shape():
    entry = {
        "message": {
            "content": [
                {"type": "tool_use", "name": "Skill", "input": {"skill": "x"}},
                {"type": "text", "text": "ignore me"},
            ]
        }
    }
    uses = mod._extract_tool_uses(entry)
    assert len(uses) == 1
    assert uses[0]["name"] == "Skill"


def test_extract_tool_uses_flattened_legacy_shape():
    entry = {"tool_name": "Skill", "tool_input": {"skill": "y"}}
    uses = mod._extract_tool_uses(entry)
    assert uses and uses[0]["name"] == "Skill"
    assert uses[0]["input"]["skill"] == "y"


def _write_transcript(tmp_path, lines):
    p = tmp_path / "transcript.jsonl"
    p.write_text("\n".join(lines), encoding="utf-8")
    return str(p)


def test_check_skill_invocations_detects_skill_tool(tmp_path):
    import json
    line = json.dumps({
        "message": {"content": [
            {"type": "tool_use", "name": "Skill",
             "input": {"skill": "suno-style-prompt-builder"}}
        ]}
    })
    skills = mod.check_skill_invocations(_write_transcript(tmp_path, [line]))
    assert "suno-style-prompt-builder" in skills


def test_check_skill_invocations_detects_agent_subagent(tmp_path):
    import json
    line = json.dumps({
        "message": {"content": [
            {"type": "tool_use", "name": "Agent",
             "input": {"prompt": "run suno-lyric-transformer headless ..."}}
        ]}
    })
    skills = mod.check_skill_invocations(_write_transcript(tmp_path, [line]))
    assert "suno-lyric-transformer" in skills


def test_check_skill_invocations_missing_path_returns_empty():
    assert mod.check_skill_invocations("") == set()


def test_main_blocks_when_pipeline_skipped(tmp_path, monkeypatch, capsys):
    import io
    import json
    payload = {
        "last_assistant_message": "## Your Suno Package\nStyle, lyrics, settings.",
        "transcript_path": "",  # no skills invoked
        "stop_hook_active": False,
    }
    monkeypatch.setattr(sys, "argv", ["pipeline-guard.py"])
    monkeypatch.setattr(sys, "stdin", io.StringIO(json.dumps(payload)))
    with pytest.raises(SystemExit) as exc:
        mod.main()
    assert exc.value.code == 0  # hooks never crash the turn
    decision = json.loads(capsys.readouterr().out)
    assert decision["decision"] == "block"
    assert "suno-style-prompt-builder" in decision["reason"]


def test_main_silent_when_no_package(tmp_path, monkeypatch, capsys):
    import io
    import json
    payload = {
        "last_assistant_message": "Just chatting, no package here.",
        "transcript_path": "",
        "stop_hook_active": False,
    }
    monkeypatch.setattr(sys, "argv", ["pipeline-guard.py"])
    monkeypatch.setattr(sys, "stdin", io.StringIO(json.dumps(payload)))
    with pytest.raises(SystemExit) as exc:
        mod.main()
    assert exc.value.code == 0
    assert capsys.readouterr().out.strip() == ""


# ---------------------------------------------------------------------------
# Structure-based lyric requirement (auto-lyrics / instrumental pass)
# ---------------------------------------------------------------------------

AUTO_LYRICS_PACKAGE = (
    "## Your Suno Package\n\n"
    "### Lyrics\nLyrics: Auto-generated by Suno — set Lyrics Mode to Auto\n\n"
    "### Style Prompt (v6)\n120/1000 characters\n\n```\nwarm folk, brushed drums\n```\n\n"
    "### Exclude Styles\n```\nautotune\n```\n\n"
    "### Settings\n- Model: v6\n\n"
    "### Song Title\n```\nPorch Light\n```\n\n"
    "### Save to\nPaper Lanterns\n\n"
    "### Wild Card Variant — The Unexpected Take\n```\n1960s coffeehouse folk\n```\n"
)

TAGGED_PACKAGE = AUTO_LYRICS_PACKAGE.replace(
    "Lyrics: Auto-generated by Suno — set Lyrics Mode to Auto",
    "```\n[Verse 1]\nThe porch light flickers on\n\n[Chorus]\nCome back home\n```",
)

INSTRUMENTAL_PACKAGE = AUTO_LYRICS_PACKAGE.replace(
    "Lyrics: Auto-generated by Suno — set Lyrics Mode to Auto",
    "Lyrics: Instrumental (no vocals)\n[Intro]\n[Build]",
)


def test_auto_lyrics_package_needs_no_lyric_transformer():
    assert not mod.needs_lyric_transformer(AUTO_LYRICS_PACKAGE)
    missing, order = mod.build_violations(AUTO_LYRICS_PACKAGE, {mod.STYLE_SKILL})
    assert missing == [] and order == []


def test_instrumental_package_needs_no_lyric_transformer():
    assert not mod.needs_lyric_transformer(INSTRUMENTAL_PACKAGE)


def test_tagged_lyrics_need_lyric_transformer():
    assert mod.needs_lyric_transformer(TAGGED_PACKAGE)
    missing, _ = mod.build_violations(TAGGED_PACKAGE, {mod.STYLE_SKILL})
    assert missing == [mod.LYRIC_SKILL]


def test_lyrics_only_refinement_needs_no_style_builder():
    msg = (
        "## Paper Lanterns Refinement Update\n### What Changed\n- tighter chorus\n\n"
        "### Copy-Ready Lyrics\n```\n[Chorus]\nCome back home\n```\n"
    )
    assert mod.detect_suno_package(msg)
    missing, _ = mod.build_violations(msg, {mod.LYRIC_SKILL})
    assert missing == []


def test_headingless_package_still_needs_style_builder():
    msg = "Here you go — paste into Suno: warm folk, brushed drums"
    assert mod.needs_style_builder(msg)


# ---------------------------------------------------------------------------
# Package order
# ---------------------------------------------------------------------------


def test_package_in_create_screen_order_passes():
    assert mod.check_package_order(AUTO_LYRICS_PACKAGE) == []
    assert mod.package_sections(AUTO_LYRICS_PACKAGE) == [
        "Lyrics", "Style Prompt", "Exclude Styles", "Settings", "Title", "Save to", "Wild Card",
    ]


def test_title_first_is_flagged():
    msg = "## Your Suno Package\n### Song Title\nX\n### Lyrics\n...\n### Style Prompt\n..."
    problems = mod.check_package_order(msg)
    assert "Lyrics should come before Title" in problems


def test_style_before_lyrics_is_flagged():
    msg = "## Your Suno Package\n### Style Prompt (v6)\n...\n### Lyrics\n..."
    assert mod.check_package_order(msg) == ["Lyrics should come before Style Prompt"]


def test_wild_card_style_prompt_heading_is_the_wild_card():
    msg = "### Lyrics\n..\n### Style Prompt\n..\n### Wild Card Style Prompt\n..\n"
    assert mod.package_sections(msg) == ["Lyrics", "Style Prompt", "Wild Card"]


def test_voice_and_persona_come_first():
    msg = "### Persona\nX\n### Lyrics\n..\n### Style Prompt\n.."
    assert mod.check_package_order(msg) == []
    bad = "### Lyrics\n..\n### Voice\nX\n"
    assert mod.check_package_order(bad) == ["Voice should come before Lyrics"]


# ---------------------------------------------------------------------------
# Turn scoping
# ---------------------------------------------------------------------------

import json as _json


def _user(text, **extra):
    return _json.dumps({"type": "user", "message": {"role": "user", "content": text}, **extra})


def _skill(name):
    return _json.dumps({"type": "assistant", "message": {"content": [
        {"type": "tool_use", "name": "Skill", "input": {"skill": name}}]}})


def _agent(prompt):
    return _json.dumps({"type": "assistant", "message": {"content": [
        {"type": "tool_use", "name": "Agent", "input": {"prompt": prompt}}]}})


def _tool_result():
    return _json.dumps({"type": "user", "message": {"content": [
        {"type": "tool_result", "content": "Launching skill"}]}})


def test_earlier_turn_invocation_does_not_count(tmp_path):
    path = _write_transcript(tmp_path, [
        _user("make me a song"),
        _skill("suno-style-prompt-builder"),
        _user("now another one"),
    ])
    assert mod.check_skill_invocations(path) == set()
    assert "suno-style-prompt-builder" in mod.check_skill_invocations(path, current_turn_only=False)


def test_tool_results_skill_bodies_and_notifications_do_not_reset_turn(tmp_path):
    path = _write_transcript(tmp_path, [
        _user("make me a song"),
        _skill("suno-style-prompt-builder"),
        _tool_result(),
        _json.dumps({"type": "user", "isMeta": True, "message": {"content": [
            {"type": "text", "text": "Base directory for this skill: ..."}]}}),
        _user("<task-notification>agent finished</task-notification>",
              origin={"kind": "task-notification"}, promptSource="system"),
        _user("Stop hook feedback: PIPELINE VIOLATION ..."),
        _agent("Invoke suno-lyric-transformer in headless mode with this poem"),
    ])
    assert mod.check_skill_invocations(path) == {
        "suno-style-prompt-builder", "suno-lyric-transformer"}


def test_agent_prompt_that_only_mentions_a_skill_does_not_count(tmp_path):
    path = _write_transcript(tmp_path, [
        _user("hi"),
        _agent("Summarize what suno-style-prompt-builder returned last week"),
    ])
    assert mod.check_skill_invocations(path) == set()


def test_main_passes_auto_lyrics_package_with_style_builder_this_turn(tmp_path, monkeypatch, capsys):
    import io
    path = _write_transcript(tmp_path, [_user("surprise me"), _skill("suno-style-prompt-builder")])
    payload = {"last_assistant_message": AUTO_LYRICS_PACKAGE, "transcript_path": path,
               "stop_hook_active": False}
    monkeypatch.setattr(sys, "argv", ["pipeline-guard.py"])
    monkeypatch.setattr(sys, "stdin", io.StringIO(_json.dumps(payload)))
    with pytest.raises(SystemExit):
        mod.main()
    assert capsys.readouterr().out.strip() == ""


def test_main_blocks_out_of_order_package(tmp_path, monkeypatch, capsys):
    import io
    path = _write_transcript(tmp_path, [_user("go"), _skill("suno-style-prompt-builder")])
    msg = "## Your Suno Package\n### Style Prompt (v6)\n..\n### Lyrics\nAuto-generated by Suno\n"
    payload = {"last_assistant_message": msg, "transcript_path": path, "stop_hook_active": False}
    monkeypatch.setattr(sys, "argv", ["pipeline-guard.py"])
    monkeypatch.setattr(sys, "stdin", io.StringIO(_json.dumps(payload)))
    with pytest.raises(SystemExit):
        mod.main()
    decision = _json.loads(capsys.readouterr().out)
    assert decision["decision"] == "block"
    assert "PACKAGE ORDER" in decision["reason"]
    assert "PIPELINE VIOLATION" not in decision["reason"]
