#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# dependencies = ["pyyaml>=6.0"]
# ///
"""Merge module configuration into shared _bmad/config.yaml and config.user.yaml.

Reads a module.yaml definition and a JSON answers file, then writes or updates
the shared config.yaml (core values at root + module section) and config.user.yaml
(user_name, communication_language, plus any module variable with user_setting: true).
Uses an anti-zombie pattern for the module section in config.yaml.

Value priority (one function, used by the preview and the merge alike):
explicit answers > existing config.yaml / config.user.yaml > per-module config
files under --legacy-dir (read only) > module.yaml / core defaults. So a value
the user hand-edited survives an update unless the answers change it.

Per-module config files are only ever read, never deleted. The script never
writes another module's files (including _bmad/core/config.yaml). It writes the
_bmad/{module}/config.yaml bridge only when no BMad installer manages _bmad/
(no _bmad/_config/manifest.yaml).

Detection pre-pass: --detect-mode classifies the install (fresh|update|standalone|
migration), reports the version transition and the defaults to show, and writes
nothing. With --answers it also returns changes:[{file,key,old,new}] — exactly
what the merge would write.

Exit codes: 0=success, 1=validation error, 2=runtime error
"""

import argparse
import json
import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    print("Error: pyyaml is required (PEP 723 dependency)", file=sys.stderr)
    sys.exit(2)


# Keys that live at config root (shared across all modules)
_CORE_KEYS = ("user_name", "communication_language", "document_output_language", "output_folder")
# Core keys that are always written to config.user.yaml
_CORE_USER_KEYS = ("user_name", "communication_language")
_CORE_DEFAULTS = {
    "user_name": "BMad",
    "communication_language": "English",
    "document_output_language": "English",
    "output_folder": "{project-root}/_bmad-output",
}
_META_KEYS = frozenset({"name", "description", "version", "default_selected"})
BRIDGE_HEADER = (
    "# Written by suno-setup (merge-config.py) on every setup run.\n"
    "# Edit _bmad/config.yaml instead; this file is regenerated from it.\n"
)
INSTALLER_HEADER = "Generated by BMAD installer"


def parse_args():
    parser = argparse.ArgumentParser(
        description="Merge module config into shared _bmad/config.yaml with anti-zombie pattern."
    )
    parser.add_argument("--config-path", required=True, help="Path to the target _bmad/config.yaml file")
    parser.add_argument("--module-yaml", required=True, help="Path to the module.yaml definition file")
    parser.add_argument(
        "--answers",
        help="Path to JSON file with collected answers (required unless --create-dirs)",
    )
    parser.add_argument(
        "--user-config-path",
        help="Path to the target _bmad/config.user.yaml file (required for the merge; "
        "optional for --detect-mode, default: next to --config-path)",
    )
    parser.add_argument(
        "--create-dirs",
        action="store_true",
        help="Directory-creation mode: read the resolved config + module.yaml "
        "'directories:' list and create any output directories that don't exist. "
        "Skips the merge entirely. Requires --project-root.",
    )
    parser.add_argument(
        "--detect-mode",
        action="store_true",
        help="Detection-only pre-pass: classify the install, report the version "
        "transition and the defaults to show, and — if --answers is given — the "
        "exact changes the merge would write. Writes nothing.",
    )
    parser.add_argument(
        "--project-root",
        help="Actual project root, used to resolve the {project-root} token on disk "
        "for --create-dirs. The stored config values keep the literal token.",
    )
    parser.add_argument(
        "--legacy-dir",
        help="Path to _bmad/ to read per-module config files from (core/config.yaml, "
        "{module}/config.yaml). Read only — used as fallback defaults, never deleted.",
    )
    parser.add_argument("--verbose", action="store_true", help="Print detailed progress to stderr")
    return parser.parse_args()


def reject_unresolved_paths(named_paths: list[tuple[str, str | None]]) -> None:
    """Exit with a clear error if any path argument still contains the literal
    ``{project-root}`` token. That token is meaningful only inside config
    values; filesystem path arguments must be resolved by the caller. Failing
    loudly here prevents silently creating a junk ``{project-root}/`` directory.
    """
    for name, value in named_paths:
        if value and "{project-root}" in value:
            print(
                json.dumps(
                    {
                        "status": "error",
                        "error": (
                            f"Unresolved '{{project-root}}' token in {name} path: {value!r}. "
                            "Resolve '{project-root}' to the actual project root before running "
                            "this script — it is a filesystem path, not a config value."
                        ),
                    },
                    indent=2,
                )
            )
            sys.exit(1)


def load_yaml_file(path) -> dict:
    """Load a YAML file, returning empty dict if file doesn't exist.

    On a malformed YAML file, exits 1 with a clean, actionable error rather
    than letting a raw YAMLError stack trace escape.
    """
    file_path = Path(path)
    if not file_path.exists():
        return {}
    try:
        with open(file_path, "r", encoding="utf-8") as f:
            content = yaml.safe_load(f)
    except yaml.YAMLError as e:
        print(
            json.dumps(
                {
                    "status": "error",
                    "error": f"Malformed YAML in {file_path}: {e}. "
                    "Fix the file by hand or delete it to recreate, then re-run.",
                }
            )
        )
        sys.exit(1)
    return content if isinstance(content, dict) else {}


def load_json_file(path: str) -> dict:
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def is_installer_managed(bmad_dir: Path) -> bool:
    """True when a BMad installer (v6.x) manages this _bmad/ directory."""
    return (bmad_dir / "_config" / "manifest.yaml").is_file()


def module_variables(module_yaml: dict) -> dict:
    """The prompted/defaulted variable definitions in module.yaml."""
    return {
        k: v
        for k, v in module_yaml.items()
        if isinstance(v, dict) and ("prompt" in v or "default" in v)
    }


def load_legacy_values(legacy_dir, module_code: str, module_yaml: dict) -> tuple[dict, dict, list]:
    """Read per-module config files (read only) and return core/module value dicts.

    Reads {legacy_dir}/core/config.yaml and {legacy_dir}/{module_code}/config.yaml.
    Only returns values whose keys match the current schema. Nothing is deleted.
    """
    legacy_core: dict = {}
    legacy_module: dict = {}
    files_found: list = []
    if not legacy_dir:
        return legacy_core, legacy_module, files_found
    variables = module_variables(module_yaml)

    core_path = Path(legacy_dir) / "core" / "config.yaml"
    if core_path.exists():
        files_found.append(str(core_path))
        for k, v in load_yaml_file(core_path).items():
            if k in _CORE_KEYS:
                legacy_core[k] = v

    mod_path = Path(legacy_dir) / module_code / "config.yaml"
    if mod_path.exists():
        files_found.append(str(mod_path))
        for k, v in load_yaml_file(mod_path).items():
            if k in _CORE_KEYS:
                legacy_core.setdefault(k, v)
            elif k in variables:
                legacy_module[k] = v

    return legacy_core, legacy_module, files_found


def apply_result_templates(module_yaml: dict, module_answers: dict, verbose: bool = False) -> dict:
    """Apply result templates from module.yaml to transform raw answer values.

    Skips the template if the answer already contains '{project-root}' to
    prevent double-prefixing.
    """
    transformed = {}
    for key, value in module_answers.items():
        var_def = module_yaml.get(key)
        if isinstance(var_def, dict) and "result" in var_def and "{project-root}" not in str(value):
            transformed[key] = var_def["result"].replace("{value}", str(value))
            if verbose:
                print(f"Applied result template for '{key}': {value} → {transformed[key]}", file=sys.stderr)
        else:
            transformed[key] = value
    return transformed


def strip_result_template(var_def: dict, stored):
    """Invert a result template for display: '{project-root}/docs/x' → 'docs/x'."""
    template = var_def.get("result") if isinstance(var_def, dict) else None
    if not template or "{value}" not in template or not isinstance(stored, str):
        return stored
    prefix, suffix = template.split("{value}", 1)
    if prefix and stored.startswith(prefix) and stored.endswith(suffix):
        return stored[len(prefix): len(stored) - len(suffix) if suffix else None]
    return stored


def resolve_values(
    existing_config: dict,
    existing_user: dict,
    module_yaml: dict,
    answers: dict,
    legacy_core: dict,
    legacy_module: dict,
) -> dict:
    """The single source of truth for what gets written.

    Returns {"core": {key: (value, source)}, "module": {key: (value, source)}}
    with module values in stored form (result templates applied). Priority:
    answers > existing > legacy/installer > defaults.
    """
    module_code = module_yaml.get("code", "")
    existing_root = dict(existing_config)
    # A legacy nested `core:` section counts as existing root values.
    if isinstance(existing_root.get("core"), dict):
        for k, v in existing_root["core"].items():
            existing_root.setdefault(k, v)
    existing_module = existing_config.get(module_code)
    if not isinstance(existing_module, dict):
        existing_module = {}
    variables = module_variables(module_yaml)

    core_answers = answers.get("core") or {}
    core: dict = {}
    for key in _CORE_KEYS:
        if key in core_answers:
            core[key] = (core_answers[key], "answer")
        elif key in _CORE_USER_KEYS and key in existing_user:
            core[key] = (existing_user[key], "existing")
        elif key in existing_root:
            core[key] = (existing_root[key], "existing")
        elif key in legacy_core:
            core[key] = (legacy_core[key], "legacy")
        else:
            core[key] = (_CORE_DEFAULTS[key], "default")

    module_answers = apply_result_templates(module_yaml, answers.get("module") or {})
    module: dict = {}
    for key, var_def in variables.items():
        user_setting = var_def.get("user_setting") is True
        if key in module_answers:
            module[key] = (module_answers[key], "answer")
        elif user_setting and key in existing_user:
            module[key] = (existing_user[key], "existing")
        elif key in existing_module:
            module[key] = (existing_module[key], "existing")
        elif key in legacy_module:
            module[key] = (apply_result_templates(module_yaml, {key: legacy_module[key]})[key], "legacy")
        elif "default" in var_def:
            module[key] = (apply_result_templates(module_yaml, {key: var_def["default"]})[key], "default")
    # Answers for keys outside the schema are still honored (caller's choice).
    for key, value in module_answers.items():
        if key not in module:
            module[key] = (value, "answer")
    return {"core": core, "module": module}


def extract_module_metadata(module_yaml: dict) -> dict:
    """Extract non-variable metadata fields from module.yaml."""
    meta = {}
    for k in ("name", "description"):
        if k in module_yaml:
            meta[k] = module_yaml[k]
    meta["version"] = module_yaml.get("module_version")  # null if absent
    if "default_selected" in module_yaml:
        meta["default_selected"] = module_yaml["default_selected"]
    return meta


def build_outputs(existing_config: dict, existing_user: dict, module_yaml: dict, resolved: dict) -> tuple[dict, dict]:
    """Build the full config.yaml and config.user.yaml contents to write."""
    module_code = module_yaml.get("code")
    if not module_code:
        print(json.dumps({"status": "error", "error": "module.yaml must have a 'code' field"}))
        sys.exit(1)
    variables = module_variables(module_yaml)

    config = dict(existing_config)
    # Migrate a legacy nested core: section to root.
    if isinstance(config.get("core"), dict):
        config.update(config.pop("core"))
    # User-only keys live exclusively in config.user.yaml.
    for key in _CORE_USER_KEYS:
        config.pop(key, None)
    for key, (value, _src) in resolved["core"].items():
        if key not in _CORE_USER_KEYS:
            config[key] = value

    # Anti-zombie: rebuild the module section from scratch.
    config.pop(module_code, None)
    section = extract_module_metadata(module_yaml)
    user = dict(existing_user)
    for key in _CORE_USER_KEYS:
        user[key] = resolved["core"][key][0]
    for key, (value, _src) in resolved["module"].items():
        if isinstance(variables.get(key), dict) and variables[key].get("user_setting") is True:
            user[key] = value
        else:
            section[key] = value
    config[module_code] = section
    return config, user


def compute_changes(existing_config: dict, existing_user: dict, new_config: dict, new_user: dict, module_code: str) -> list:
    """Diff existing files against what the merge will write.

    Covers core keys at the config root, every module-section key (including
    keys the anti-zombie rewrite drops, reported with new: null) and every
    config.user.yaml key. Module metadata (name/description/version) is left
    out — the version change is reported as version_transition.
    """
    changes: list = []
    for key in _CORE_KEYS:
        if key in _CORE_USER_KEYS:
            continue
        old = existing_config.get(key)
        if isinstance(existing_config.get("core"), dict) and old is None:
            old = existing_config["core"].get(key)
        new = new_config.get(key)
        if old != new:
            changes.append({"file": "config", "key": key, "old": old, "new": new})

    old_section = existing_config.get(module_code)
    old_section = old_section if isinstance(old_section, dict) else {}
    new_section = new_config.get(module_code, {})
    for key in list(dict.fromkeys([*old_section, *new_section])):
        if key in _META_KEYS:
            continue
        old, new = old_section.get(key), new_section.get(key)
        if old != new:
            changes.append({"file": "config", "key": key, "old": old, "new": new})

    for key in list(dict.fromkeys([*existing_user, *new_user])):
        old, new = existing_user.get(key), new_user.get(key)
        if old != new:
            changes.append({"file": "user_config", "key": key, "old": old, "new": new})
    return changes


def write_config(config: dict, config_path, verbose: bool = False, header: str = "") -> None:
    """Write config dict to YAML file, creating parent dirs as needed."""
    path = Path(config_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    if verbose:
        print(f"Writing config to {path}", file=sys.stderr)
    with open(path, "w", encoding="utf-8") as f:
        f.write(header)
        yaml.dump(config, f, default_flow_style=False, allow_unicode=True, sort_keys=False)


def write_bridge_config(config: dict, user_config: dict, module_code: str, bmad_dir: Path, verbose=False) -> tuple[list, list]:
    """Write the flat _bmad/{module}/config.yaml bridge (core + module values).

    The module's audio scripts read this file before the shared config.yaml.
    Skipped when a BMad installer manages _bmad/ — per-module config files are
    the installer's then — or when the file carries the installer's header.
    Never writes _bmad/core/config.yaml or any other module's files.
    """
    path = bmad_dir / module_code / "config.yaml"
    if is_installer_managed(bmad_dir):
        return [], [{"path": str(path), "reason": "installer_managed"}]
    if path.is_file() and INSTALLER_HEADER in path.read_text(encoding="utf-8")[:400]:
        return [], [{"path": str(path), "reason": "installer_generated"}]
    values = {k: config[k] for k in _CORE_KEYS if k in config}
    values.update({k: user_config[k] for k in _CORE_USER_KEYS if k in user_config})
    for key, value in config.get(module_code, {}).items():
        if key not in _META_KEYS:
            values[key] = value
    write_config(values, path, verbose, header=BRIDGE_HEADER)
    return [str(path)], []


def resolve_output_directories(config: dict, module_yaml: dict) -> list:
    """Collect the output directories that should exist on disk.

    Honors the module.yaml `directories:` declaration (entries may reference
    module variables like `{band_profiles_folder}`) plus the shared
    `output_folder`. Values keep the literal `{project-root}` token.
    """
    module_section = config.get(module_yaml.get("code", ""), {})
    candidates = []
    if config.get("output_folder"):
        candidates.append(str(config["output_folder"]))
    for entry in module_yaml.get("directories", []) or []:
        value = str(entry)
        for var_name, var_value in module_section.items():
            value = value.replace("{" + var_name + "}", str(var_value))
        candidates.append(value)
    return list(dict.fromkeys(v for v in candidates if "{project-root}" in v))


def create_output_dirs(config: dict, module_yaml: dict, project_root: str) -> dict:
    """Create configured output directories on disk, resolving {project-root}."""
    created, existed = [], []
    for value in resolve_output_directories(config, module_yaml):
        disk_path = Path(value.replace("{project-root}", project_root))
        if disk_path.exists():
            existed.append(value)
        else:
            disk_path.mkdir(parents=True, exist_ok=True)
            created.append(value)
    return {"created": created, "existed": existed}


def detect_mode(config_path: str, module_yaml: dict, legacy_dir: str | None) -> dict:
    """Classify the installation deterministically.

    mode:
      - standalone : no _bmad/ directory yet
      - update     : config.yaml already has this module's section
      - migration  : per-module config from an earlier installer exists, no
                     module section, and no BMad installer manages _bmad/
      - fresh      : anything else (including a v6.x installer-managed _bmad/,
                     whose per-module configs are the installer's, not legacy)

    cleanup_needed is true only for migration — the one mode where
    cleanup-legacy.py may have leftover module copies to remove.
    """
    module_code = module_yaml.get("code", "")
    bmad_dir = Path(config_path).parent
    existing_config = load_yaml_file(config_path)
    has_module_section = isinstance(existing_config.get(module_code), dict)
    installer_managed = is_installer_managed(bmad_dir)

    legacy_root = Path(legacy_dir) if legacy_dir else bmad_dir
    per_module_configs = (legacy_root / module_code / "config.yaml").exists() or (
        legacy_root / "core" / "config.yaml"
    ).exists()
    has_legacy = per_module_configs and not installer_managed

    if not bmad_dir.exists():
        mode = "standalone"
    elif has_module_section:
        mode = "update"
    elif has_legacy:
        mode = "migration"
    else:
        mode = "fresh"

    existing_version = existing_config[module_code].get("version") if has_module_section else None
    return {
        "status": "success",
        "mode": mode,
        "has_module_section": has_module_section,
        "has_legacy": has_legacy,
        "installer_managed": installer_managed,
        "cleanup_needed": mode == "migration",
        "has_core": any(k in existing_config for k in _CORE_KEYS if k not in _CORE_USER_KEYS),
        "version_transition": {"from": existing_version, "to": module_yaml.get("module_version")},
    }


def display_defaults(resolved: dict, module_yaml: dict) -> dict:
    """Defaults to show the user, in answer form ('docs/x', not '{project-root}/docs/x')."""
    variables = module_variables(module_yaml)
    return {
        "core": {k: {"value": v, "source": s} for k, (v, s) in resolved["core"].items()},
        "module": {
            k: {"value": strip_result_template(variables.get(k, {}), v), "source": s}
            for k, (v, s) in resolved["module"].items()
        },
    }


def main():
    args = parse_args()
    reject_unresolved_paths(
        [
            ("--config-path", args.config_path),
            ("--user-config-path", args.user_config_path),
            ("--module-yaml", args.module_yaml),
            ("--answers", args.answers),
            ("--legacy-dir", args.legacy_dir),
            ("--project-root", args.project_root),
        ]
    )

    module_yaml = load_yaml_file(args.module_yaml)
    if not module_yaml:
        print(json.dumps({"status": "error", "error": f"Could not load module.yaml from {args.module_yaml}"}))
        sys.exit(1)
    module_code = module_yaml.get("code", "")

    if args.create_dirs:
        if not args.project_root:
            print(json.dumps({"status": "error", "error": "--project-root is required with --create-dirs"}))
            sys.exit(1)
        result = create_output_dirs(load_yaml_file(args.config_path), module_yaml, args.project_root)
        result["status"] = "success"
        print(json.dumps(result, indent=2))
        return

    config_path = Path(args.config_path)
    user_config_path = Path(args.user_config_path) if args.user_config_path else config_path.parent / "config.user.yaml"
    legacy_dir = args.legacy_dir or str(config_path.parent)
    existing_config = load_yaml_file(config_path)
    existing_user = load_yaml_file(user_config_path)
    legacy_core, legacy_module, legacy_files = load_legacy_values(legacy_dir, module_code, module_yaml)

    if args.detect_mode:
        result = detect_mode(args.config_path, module_yaml, args.legacy_dir)
        answers = load_json_file(args.answers) if args.answers else {}
        resolved = resolve_values(existing_config, existing_user, module_yaml, answers, legacy_core, legacy_module)
        result["defaults"] = display_defaults(
            resolve_values(existing_config, existing_user, module_yaml, {}, legacy_core, legacy_module), module_yaml
        )
        if args.answers:
            new_config, new_user = build_outputs(existing_config, existing_user, module_yaml, resolved)
            result["changes"] = compute_changes(existing_config, existing_user, new_config, new_user, module_code)
        print(json.dumps(result, indent=2))
        return

    if not args.answers or not args.user_config_path:
        print(json.dumps({"status": "error", "error": "--answers and --user-config-path are required for merge mode"}))
        sys.exit(1)

    answers = load_json_file(args.answers)
    resolved = resolve_values(existing_config, existing_user, module_yaml, answers, legacy_core, legacy_module)
    new_config, new_user = build_outputs(existing_config, existing_user, module_yaml, resolved)
    changes = compute_changes(existing_config, existing_user, new_config, new_user, module_code)

    write_config(new_config, config_path, args.verbose)
    if new_user != existing_user or not user_config_path.exists():
        write_config(new_user, user_config_path, args.verbose)

    written, skipped = write_bridge_config(new_config, new_user, module_code, config_path.parent, args.verbose)

    print(
        json.dumps(
            {
                "status": "success",
                "config_path": str(config_path.resolve()),
                "user_config_path": str(user_config_path.resolve()),
                "module_code": module_code,
                "module_keys": list(new_config.get(module_code, {}).keys()),
                "user_keys": list(new_user.keys()),
                "changes": changes,
                "legacy_configs_read": legacy_files,
                "init_configs_written": written,
                "init_configs_skipped": skipped,
            },
            indent=2,
        )
    )


if __name__ == "__main__":
    main()
