#!/usr/bin/env python3
# /// script
# requires-python = ">=3.11"
# dependencies = ["pyyaml>=6.0", "pytest"]
# ///
"""End-to-end safety tests: run the setup scripts, in the order SKILL.md runs
them, against a temp copy of a BMad v6.12 installer-managed _bmad/ tree.

The fixture is modelled on a real v6.12.1 install (installer manifest and help
catalog under _config/, installer-written core/ and per-module configs,
v6-shims, other modules' folders, the agent's memory). The tests assert that
everything the installer or another module owns survives byte-for-byte, that
the update preview matches what the merge writes, and that hand-edited values
are kept.
"""

import csv
import hashlib
import json
import subprocess
import sys
from io import StringIO
from pathlib import Path

import yaml

SKILL = Path(__file__).resolve().parent.parent.parent
SCRIPTS = SKILL / "scripts"
MODULE_YAML = SKILL / "assets" / "module.yaml"
MODULE_HELP = SKILL / "assets" / "module-help.csv"
CANONICAL = ("module,skill,display-name,menu-code,description,action,args,phase,"
             "preceded-by,followed-by,required,output-location,outputs")
INSTALLER_HEADER = ("# {mod} Module Configuration\n# Generated by BMAD installer\n"
                    "# Version: 6.12.1-next.0\n# Date: 2026-10-03T20:34:48.746Z\n\n")
CORE_VALUES = ('user_name: Ada\nproject_name: demo-project\ncommunication_language: English\n'
               'document_output_language: English\noutput_folder: "{project-root}/_bmad-output"\n')

# Paths (relative to _bmad/) that setup must never change.
PROTECTED = [
    "_config", "core", "bmm", "bmb", "_memory", "scripts", "custom", "render",
    "config.toml", "config.user.toml", "suno/config.yaml",
]


def write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def build_v612_tree(root: Path, with_suno_section: bool = True) -> Path:
    """A de-identified v6.12 installer-managed _bmad/ plus a prior suno setup."""
    bmad = root / "_bmad"
    write(bmad / "_config" / "manifest.yaml",
          "installation:\n  version: 6.12.1-next.0\n  installShims: false\n"
          "modules:\n  - name: core\n    version: 6.12.1-next.0\n    source: built-in\n"
          "  - name: bmm\n    version: 6.12.1-next.0\n    source: built-in\n"
          "  - name: bmb\n    version: v2.2.2\n    source: external\n"
          "ides:\n  - claude-code\n  - gemini\n")
    write(bmad / "_config" / "files-manifest.csv",
          'type,name,module,path,hash\n'
          '"yaml","manifest","_config","_config/manifest.yaml","aa"\n'
          '"csv","module-help","bmb","bmb/module-help.csv","bb"\n'
          '"yaml","config","suno","suno/config.yaml","cc"\n')
    write(bmad / "_config" / "skill-manifest.csv",
          'canonicalId,name,description,module,path\n'
          '"bmad-brainstorming","bmad-brainstorming","Brainstorm","core","_bmad/core/bmad-brainstorming/SKILL.md"\n')
    write(bmad / "_config" / "agent-manifest.csv", "name,displayName,title,icon,module,path,canonicalId\n")
    write(bmad / "_config" / "bmad-help.csv",
          CANONICAL + "\nCore,bmad-brainstorming,Brainstorming,BSP,Ideate.,,,anytime,,,false,,session\n")
    (bmad / "_config" / "agents").mkdir(parents=True)
    (bmad / "_config" / "custom").mkdir(parents=True)
    write(bmad / "core" / "config.yaml", INSTALLER_HEADER.format(mod="CORE") + CORE_VALUES)
    write(bmad / "core" / "module-help.csv",
          CANONICAL + "\nCore,_meta,,,,,,,,,false,https://docs.bmad-method.org/,\n")
    write(bmad / "core" / "v6-shims" / "README.md", "shims\n")
    write(bmad / "bmm" / "config.yaml", INSTALLER_HEADER.format(mod="BMM") + "user_skill_level: intermediate\n")
    write(bmad / "bmm" / "module-help.csv", CANONICAL + "\n")
    write(bmad / "bmm" / "v6-shims" / "README.md", "shims\n")
    write(bmad / "bmb" / "config.yaml", INSTALLER_HEADER.format(mod="BMB") + 'bmad_builder_output_folder: "{project-root}/skills"\n')
    write(bmad / "bmb" / "module-help.csv", CANONICAL + "\n")
    write(bmad / "bmb" / "bmad-module-builder" / "SKILL.md", "---\nname: bmad-module-builder\n---\n")
    write(bmad / "suno" / "config.yaml", INSTALLER_HEADER.format(mod="SUNO") + "# Core Configuration Values\n" + CORE_VALUES)
    write(bmad / "config.toml", '[core]\nproject_name = "demo-project"\n')
    write(bmad / "config.user.toml", '[core]\nuser_name = "Ada"\n')
    write(bmad / "custom" / "config.toml", "")
    write(bmad / "scripts" / "resolve_config.py", "# stub\n")
    write(bmad / "render" / ".gitignore", "*\n")
    write(bmad / "_memory" / "band-manager-sidecar" / "MEMORY.md", "memory\n")
    # A prior suno setup run (hand-edited afterwards).
    if with_suno_section:
        write(bmad / "config.yaml",
              "document_output_language: English\n"
              "output_folder: '{project-root}/my-output'\n"  # hand-edited
              "suno:\n  name: Suno Band Manager\n  version: 2.0.0\n"
              "  suno_tier: pro\n  default_mode: studio\n"
              "  band_profiles_folder: '{project-root}/docs/band-profiles'\n"
              "  songbook_folder: '{project-root}/docs/songbook'\n"
              "  pytorch_audio_tools: 'on'\n")
        write(bmad / "config.user.yaml", "user_name: Grace\ncommunication_language: English\n")  # hand-edited
        write(bmad / "module-help.csv",
              CANONICAL.replace("preceded-by,followed-by", "after,before")
              + "\nSuno Band Manager,suno-old,Old,OL,old,run,,anytime,,,false,,\n")
    # Installed skills folder.
    for name in ("suno-agent-band-manager", "suno-setup"):
        write(root / ".claude" / "skills" / name / "SKILL.md", f"---\nname: {name}\n---\n")
    return bmad


def snapshot(bmad: Path) -> dict:
    """Hash every file under the protected paths."""
    digests = {}
    for rel in PROTECTED:
        target = bmad / rel
        files = [target] if target.is_file() else sorted(p for p in target.rglob("*") if p.is_file())
        for f in files:
            digests[str(f.relative_to(bmad))] = hashlib.sha256(f.read_bytes()).hexdigest()
        if target.is_dir() and not files:
            digests[rel + "/"] = "dir"
    return digests


def run(script: str, *args: str) -> dict:
    result = subprocess.run([sys.executable, str(SCRIPTS / script), *args], capture_output=True, text=True)
    assert result.returncode == 0, (script, result.stdout, result.stderr)
    return json.loads(result.stdout)


def run_setup(root: Path, answers: dict) -> dict:
    """The documented command sequence: detect → preview → merge ×3 → dirs → cleanup."""
    bmad = root / "_bmad"
    answers_file = root / "answers.json"
    answers_file.write_text(json.dumps(answers))
    common = ["--config-path", str(bmad / "config.yaml"), "--module-yaml", str(MODULE_YAML)]
    out = {"detect": run("merge-config.py", "--detect-mode", *common, "--legacy-dir", str(bmad))}
    out["preview"] = run("merge-config.py", "--detect-mode", *common, "--legacy-dir", str(bmad),
                         "--answers", str(answers_file))
    out["merge"] = run("merge-config.py", *common, "--user-config-path", str(bmad / "config.user.yaml"),
                       "--answers", str(answers_file), "--legacy-dir", str(bmad))
    out["csv_root"] = run("merge-help-csv.py", "--target", str(bmad / "module-help.csv"), "--source", str(MODULE_HELP))
    out["csv_module"] = run("merge-help-csv.py", "--target", str(bmad / "suno" / "module-help.csv"),
                            "--source", str(MODULE_HELP))
    out["dirs"] = run("merge-config.py", "--create-dirs", *common, "--project-root", str(root))
    out["cleanup"] = run("cleanup-legacy.py", "--bmad-dir", str(bmad), "--module-code", "suno",
                         "--skills-dir", str(root / ".claude" / "skills"), "--dry-run")
    return out


def test_update_run_leaves_installer_state_untouched(tmp_path):
    bmad = build_v612_tree(tmp_path)
    before = snapshot(bmad)
    out = run_setup(tmp_path, {"module": {"suno_tier": "pro"}})
    assert out["detect"]["mode"] == "update"
    assert out["detect"]["installer_managed"] is True
    assert out["detect"]["cleanup_needed"] is False
    assert snapshot(bmad) == before
    core = (bmad / "core" / "config.yaml").read_text()
    assert "project_name: demo-project" in core and "Generated by BMAD installer" in core
    assert out["merge"]["init_configs_written"] == []
    assert out["cleanup"]["would_remove"] == []


def test_cleanup_real_run_on_v612_tree_removes_nothing_protected(tmp_path):
    """Even if cleanup is run when it shouldn't be, it only touches suno-* copies."""
    bmad = build_v612_tree(tmp_path)
    write(bmad / "suno" / "suno-agent-band-manager" / "SKILL.md", "---\nname: x\n---\n")  # leftover copy
    write(bmad / "suno" / "notes.txt", "keep me\n")
    before = snapshot(bmad)
    out = run("cleanup-legacy.py", "--bmad-dir", str(bmad), "--module-code", "suno",
              "--skills-dir", str(tmp_path / ".claude" / "skills"))
    assert snapshot(bmad) == before
    assert [r["path"] for r in out["removed"]] == ["suno/suno-agent-band-manager"]
    assert (bmad / "suno" / "notes.txt").exists()
    assert (bmad / "suno" / "config.yaml").exists()


def test_preview_matches_merge_and_keeps_hand_edits(tmp_path):
    bmad = build_v612_tree(tmp_path)
    before_cfg = yaml.safe_load((bmad / "config.yaml").read_text())
    before_user = yaml.safe_load((bmad / "config.user.yaml").read_text())
    # The user changes only the tier; everything else is left to the script.
    out = run_setup(tmp_path, {"module": {"suno_tier": "premier"}})
    after_cfg = yaml.safe_load((bmad / "config.yaml").read_text())
    after_user = yaml.safe_load((bmad / "config.user.yaml").read_text())
    # Hand-edited values survive (they used to be reset from core/config.yaml).
    assert after_cfg["output_folder"] == "{project-root}/my-output"
    assert after_user["user_name"] == "Grace"
    assert after_cfg["suno"]["pytorch_audio_tools"] == "on"
    # The preview is exactly the written delta.
    written = []
    for key in ("document_output_language", "output_folder"):
        if before_cfg.get(key) != after_cfg.get(key):
            written.append(("config", key))
    for key in set(before_cfg["suno"]) | set(after_cfg["suno"]):
        if key not in ("name", "description", "version", "default_selected") and \
                before_cfg["suno"].get(key) != after_cfg["suno"].get(key):
            written.append(("config", key))
    for key in set(before_user) | set(after_user):
        if before_user.get(key) != after_user.get(key):
            written.append(("user_config", key))
    previewed = [(c["file"], c["key"]) for c in out["preview"]["changes"]]
    assert sorted(previewed) == sorted(written) == [("config", "suno_tier")]
    assert out["merge"]["changes"] == out["preview"]["changes"]


def test_help_csv_header_migrated_and_module_source_written(tmp_path):
    bmad = build_v612_tree(tmp_path)
    out = run_setup(tmp_path, {})
    assert out["csv_root"]["header_migrated"] is True
    root_rows = list(csv.reader(StringIO((bmad / "module-help.csv").read_text())))
    assert ",".join(root_rows[0]) == CANONICAL
    assert "suno-old" not in [r[1] for r in root_rows[1:] if r]
    # The per-module copy the v6.12 installer merges into bmad-help.csv.
    mod_rows = list(csv.reader(StringIO((bmad / "suno" / "module-help.csv").read_text())))
    assert ",".join(mod_rows[0]) == CANONICAL
    assert len(mod_rows) - 1 == len(list(csv.reader(StringIO(MODULE_HELP.read_text())))) - 1


def test_fresh_install_into_v612_is_not_migration(tmp_path):
    bmad = build_v612_tree(tmp_path, with_suno_section=False)
    before = snapshot(bmad)
    out = run_setup(tmp_path, {})
    assert out["detect"]["mode"] == "fresh"
    assert out["detect"]["cleanup_needed"] is False
    # Core defaults come from the installer's config (read only).
    assert out["detect"]["defaults"]["core"]["user_name"] == {"value": "Ada", "source": "legacy"}
    assert out["detect"]["defaults"]["module"]["band_profiles_folder"]["value"] == "docs/band-profiles"
    assert snapshot(bmad) == before


def test_legacy_migration_without_installer_cleans_only_suno_copies(tmp_path):
    """Pre-consolidation leftovers, no installer manifest: cleanup is needed and scoped."""
    bmad = tmp_path / "_bmad"
    write(bmad / "suno" / "config.yaml", "suno_tier: premier\nuser_name: Ada\n")
    write(bmad / "suno" / "module-help.csv", CANONICAL + "\n")
    write(bmad / "suno" / "suno-agent-band-manager" / "SKILL.md", "---\nname: x\n---\n")
    write(bmad / "suno" / "suno-agent-band-manager" / "references" / "a.md", "x\n")
    write(bmad / "core" / "config.yaml", "user_name: Ada\nproject_name: demo\n")
    write(bmad / "core" / "module-help.csv", CANONICAL + "\n")
    write(bmad / "bmm" / "config.yaml", "x: 1\n")
    write(tmp_path / ".claude" / "skills" / "suno-agent-band-manager" / "SKILL.md", "---\nname: x\n---\n")
    protected = {p: p.read_bytes() for p in (bmad / "core" / "config.yaml", bmad / "core" / "module-help.csv",
                                            bmad / "bmm" / "config.yaml", bmad / "suno" / "module-help.csv")}
    out = run_setup(tmp_path, {})
    assert out["detect"]["mode"] == "migration"
    assert out["detect"]["cleanup_needed"] is True
    assert out["detect"]["defaults"]["module"]["suno_tier"] == {"value": "premier", "source": "legacy"}
    assert [r["path"] for r in out["cleanup"]["would_remove"]] == ["suno/suno-agent-band-manager"]
    assert (bmad / "suno" / "suno-agent-band-manager").exists()  # dry run
    real = run("cleanup-legacy.py", "--bmad-dir", str(bmad), "--module-code", "suno",
               "--skills-dir", str(tmp_path / ".claude" / "skills"))
    assert real["files_removed_count"] == 2
    assert not (bmad / "suno" / "suno-agent-band-manager").exists()
    for path, data in protected.items():
        # suno/module-help.csv is rewritten by the merge; the rest are untouched.
        if path.name == "module-help.csv" and path.parent.name == "suno":
            assert path.exists()
        else:
            assert path.read_bytes() == data, path
    bridge = (bmad / "suno" / "config.yaml").read_text()
    assert bridge.startswith("# Written by suno-setup")
    assert "suno_tier: premier" in bridge
